version: "3.7"
services:
  mysql:
    container_name: mysql-ms
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: zafu
      MYSQL_PASSWORD: zafu
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - ms-network

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.28
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ms-network

  kibana:
    container_name: kibana
    image: kibana:7.17.28
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ms-network

  redis:
    container_name: redis
    image: bitnami/redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/bitnami/redis/data
    networks:
      - ms-network


  mail-dev:
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  ms-network:
    driver: bridge


volumes:
  es_data:
  db_data:
  kafka_data:
  cache_data: