spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:mysql://localhost:3307/bookdb?createDatabaseIfNotExist=true
    username: zafu
    password: zafu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  google-book:
    url: https://www.googleapis.com/books
    api-key: ${GOOGLE_BOOK_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  default-image: https://res.cloudinary.com/dht3r2jor/image/upload/v1742018621/upload/default_image.webp

server:
  port: 8010
  tomcat:
    max-swallow: -1