spring:
  datasource:
    url: jdbc:mysql://localhost:3307/orderdb?createDatabaseIfNotExist=true
    username: zafu
    password: zafu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "OC:org.zafu.orderservice.dto.request.OrderConfirmation"

app:
  client:
    book-url: http://localhost:8010/api/v1
    cart-url: http://localhost:8030/api/v1
    payment-url: http://localhost:8050/api/v1

server:
  port: 8040
