spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  data:
    redis:
      database: 0
      host: localhost
      port: 6379


#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    config-url: ${server.servlet.context-path}/v3/api-docs/swagger-config
#    url: ${server.servlet.context-path}/v3/api-docs
#    urls:
#      - name: book-service
#        url: /books/v3/api-docs
#      - name: cart-service
#        url: /carts/v3/api-docs
#      - name: order-service
#        url: /orders/v3/api-docs
#      - name: user-service
#        url: /users/v3/api-docs
#      - name: payment-service
#        url: /payments/v3/api-docs

springdoc:
  swagger-ui:
    config-url: "/swagger-config.json"