spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888


springdoc:
  swagger-ui:
    path: /payments/v3/api-docs/swagger-ui
  api-docs:
    path: /payments/v3/api-docs
