spring:
  application:
    name: cart-service
  config:
    import: optional:configserver:http://localhost:8888


springdoc:
  swagger-ui:
    path: /carts/v3/api-docs/swagger-ui
  api-docs:
    path: /carts/v3/api-docs